#!/bin/bash

ENV_EXPANSE_ADMIN_PASSWORD=${ENV_EXPANSE_ADMIN_PASSWORD:-}

if [[ "$ENV_EXPANSE_ADMIN_PASSWORD" == "" ]]; then
  echo "Requires ENV_EXPANSE_ADMIN_PASSWORD set as env variables"
  exit 1
fi

is_running=$(docker ps -f name=expanse-db -f status=running | grep postgres)
is_shutdown=$(docker ps -f name=expanse-db -f status=exited | grep postgres)

if [[ "${is_running}" != "" ]]; then
  echo "Postgress is already running in a container"
elif [[ "${is_shutdown}" != "" ]]; then
  echo "Postgres already installed, just not running"
else
  echo "Creating container and starting postgres"

  mkdir -p ~/data/expanse-db

  docker run -d \
    --name expanse-db \
    -v ~/data/expanse-db:/var/lib/postgresql/data \
    -p 54320:5432 \
    -e POSTGRES_PASSWORD="${ENV_EXPANSE_ADMIN_PASSWORD}" \
    postgres:11
fi
